name: Deploy

on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Xcode Select
      uses: devbotsxyz/xcode-select@v1.0.0
      with:
        version: "12.4.0" 
    - name: Generate archive
      run: ./build.sh --release ${{ steps.get_version.outputs.VERSION }}
